### ISSUE TITLE
Where we should add the migration?

### ISSUE THREAD

**Issue by rluvaton** [eveningkid/denodb-documentation#2]
I think we should add the migrations to the docs.

I think the tab should be here:
![suggestion](https://user-images.githubusercontent.com/16746759/103463358-6bf83980-4d34-11eb-9836-0f96f90523be.png)

And the sidebar will have the migration to the new connectors

**Comment by rluvaton** [comment]
@eveningkid How the documentation page is generated? it seems like the project icon in the navbar isn't aligned to left

**Comment by eveningkid** [comment]
Hey Raz,

How come did I miss this issue!

I think it's been a while since the shift has been done. I'm glad you worked on it, it looks great now.

Probably not many people will still need to upgrade to the new syntax so let's not add it onto the website.

Have a great day :)
